#![no_std]
#![no_main]

use rmk::macros::rmk_keyboard;

mod codex;

// Vial config is automatically generated by `build.rs`, according to `vial.json`
// Please put `vial.json` at your project's root
#[rmk_keyboard]
mod keyboard {
    #[register_processor(event)]
    fn codex_processor() -> crate::codex::CodexProcessor {
        crate::codex::CodexProcessor::new()
    }
}
